### ISSUE TITLE
How do you set the package for production?

### ISSUE THREAD

**Issue by reilg** [jfcote87/docusign#3]
Hi

Thank you for this package but I'm having a bit of trouble.

When I used `www.docusign.net` as my host it gave me an error:

```
Status: 401  AUTHORIZATION_INVALID_TOKEN: The access token provided is expired, revoked or malformed.
```

I saw that you updated the README recently and said this has been deprecated.
Does this not work for the Docusign production API anymore?

EDIT:
Sorry, adding more details. 

I've already gone through the going live process. I have a production Integrator Key, Account ID but I'm getting the error message above when I change the `Host` to `www` from `demo`.

When I use the demo credentials and URL, it works fine.

**Comment by jfcote87** [comment]
The docusign package still works in production.   Are you using the OAuth credential or a login/password?  

The new package was developed to automate creation of the package based upon DocuSign's Swagger definition file to implement all functionality.

**Comment by reilg** [comment]
> The docusign package still works in production. Are you using the OAuth credential or a login/password?

I am using code similar to `ExampleConfig()`. So I'm not really sure because it both uses a user/pass and the method is named `OauthCredential()`.

**Comment by jfcote87** [comment]
I'd need to see how you are setting up the Config. 
 
Are you receiving the error when calling cfg.OauthCredential(ctx) or when making a later call?  Could you create a gist showing your code.

**Comment by reilg** [comment]
@jfcote87 - yes of course. This is pretty much how I use it.

```go
func auth() (*docusign.Service, error) {
	ctx := context.Background()

	// get access token
	config := &docusign.Config{
		UserName:      "user@email.com",
		Password:      "password",
		IntegratorKey: "int-key",
		AccountId:     "account-id",
		Host:          "www.docusign.com",
	}

	auth, err := config.OauthCredential(ctx)
	if err != nil {
		return nil, err
	}

	cred := &docusign.OauthCredential{
		AccessToken: auth.AccessToken,
		AccountId:   "account-id",
		Host:        "www.docusign.com",
	}

	sv := docusign.New(cred, "")
	return sv, nil
}

func send() (string, error) {
	// .. envelope created here
	
	ctx := context.Background()
	sv, err := auth()
	if err != nil {
		return "", err
	}

	rsp, err := sv.EnvelopeCreate(ctx, env, upDocs...)
	if err != nil {
		return "", err // <- this is where it fails
	}

	return rsp.EnvelopeId, nil
}
```

Error message:
```
Status: 401  AUTHORIZATION_INVALID_TOKEN: The access token provided is expired, revoked or malformed
```
The funny thing here is this all works if I used demo credentials.

**Comment by jfcote87** [comment]
1. You should use www.docusign.net or na1.docusign.net as the host.

2. You shouldn't create a new Oauthcredential each time.  A token only
needs to be created once and should be stored for later reuse.  You can
just use the config struct as a credential.
    What happens if you use

func auth() (*docusign.Service) {
    return sv := docusign.New(&docusign.Config{
            UserName:      "user@email.com",
            Password:      "password",
            IntegratorKey: "int-key",
            AccountId:     "account-id",
            Host:          "www.docusign.net",
         }, "")
}

**Comment by reilg** [comment]
Hi @jfcote87 - it looks like changing the Host worked. I had thought that getting the base URL for the API was done through this package, I guess I didn't really understand the code as I thought. 

Regarding the token, doesn't it expiration of 8 hours or something? My usage doesn't come close to that atm but you're right, I should probably add a check and make sure to reuse valid tokens.

**Comment by jfcote87** [comment]
The oauth token in the this version never expires.  The Oauth2 tokens which
are used in the esign package last 8 hours and can be made to refresh.
Glad this is working for you.

**Comment by reilg** [comment]
hi @jfcote87 - sorry for the incredibly late reply but yes, this worked for me. Thank you.

> The Oauth2 tokens which
> are used in the esign package last 8 hours and can be made to refresh.

Is this also true for JWT grant authentications? I cannot seem to find this info in the docs.

**Comment by jfcote87** [comment]
Jwt expires in  1 hour

**Comment by reilg** [comment]
Ok, gotcha. Awesome. Thank you again.

PS. Do you have like a Patreon account or something?

**Comment by jfcote87** [comment]
Are using the esign package now?

**Comment by reilg** [comment]
I just started today, yeah.
